version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 5
    rebase-strategy: auto
    schedule:
      interval: weekly
      day: friday
      time: "23:00"
      timezone: Europe/Amsterdam
  - package-ecosystem: nuget
    directory: /
    open-pull-requests-limit: 5
    rebase-strategy: auto
    schedule:
      interval: weekly
      day: friday
      time: "23:00"
      timezone: Europe/Amsterdam
    groups:
      Beckhoff:
        patterns:
          - "Beckhoff.TwinCAT.Ads"
          - "Beckhoff.TwinCAT.Ads.*"
      MSTest:
        patterns:
          - "MSTest.*"
      Coverlet:
        patterns:
          - "coverlet.*"
      IOAbstraction:
        patterns:
          - "System.IO.Abstractions"
          - "System.IO.Abstractions.*"
      Analyzers:
        patterns:
          - "*Analyzer*"
