version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 5
    rebase-strategy: auto
    schedule:
      interval: weekly
      day: friday
      time: "23:00"
      timezone: Europe/Amsterdam
  - package-ecosystem: nuget
    directory: /
    open-pull-requests-limit: 5
    rebase-strategy: auto
    schedule:
      interval: weekly
      day: friday
      time: "23:00"
      timezone: Europe/Amsterdam
