<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{65800fe3-bb5f-43d1-b26a-4a3b6ac53c7a}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
]]></Declaration>
    <Implementation>
      <ST><![CDATA[ResetWriteData(Ads.WriteTestData.WriteGenericUpdatesTheValueInPlc);
ResetWriteData(Ads.WriteTestData.WriteGenericUpdatesTheValueInPlcAsync);
ResetWriteData(Ads.WriteTestData.WriteMultipleUpdatesTheValueInPlc);
ResetWriteData(Ads.WriteTestData.WriteMultipleUpdatesTheValueInPlcAsync);
ResetWriteData(Ads.WriteTestData.WriteUpdatesTheValueInPlc);
ResetWriteData(Ads.WriteTestData.WriteUpdatesTheValueInPlcAsync);

ResetWriteData(Opc.WriteTestData.WriteGenericUpdatesTheValueInPlc);
ResetWriteData(Opc.WriteTestData.WriteGenericUpdatesTheValueInPlcAsync);
ResetWriteData(Opc.WriteTestData.WriteMultipleUpdatesTheValueInPlc);
ResetWriteData(Opc.WriteTestData.WriteMultipleUpdatesTheValueInPlcAsync);
ResetWriteData(Opc.WriteTestData.WriteUpdatesTheValueInPlc);
ResetWriteData(Opc.WriteTestData.WriteUpdatesTheValueInPlcAsync);
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>