name: .NET
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches:
      - 'main'

env:
  # Stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  Owner: ${{ github.repository_owner }}
  # GitHub Packages Feed settings
  GITHUB_FEED: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
  GITHUB_KEY: ${{ secrets.GITHUB_TOKEN }}
  # Official NuGet Feed settings
  NUGET_FEED: https://api.nuget.org/v3/index.json
  NUGET_KEY: ${{ secrets.NUGET_KEY }}
  SOLUTION_NAME: PlcInterface.sln
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        dotnet-version: ['6.0.x' ]
    runs-on: ${{ matrix.os }}
    outputs:
        publicRelease: ${{ steps.nbgv.outputs.PublicRelease }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.0
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
      - name: Setup .NET
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Nerdbank.GitVersioning
        id: nbgv
        uses: dotnet/nbgv@v0.4.0
      - name: Restore dependencies
        run: dotnet restore ${{ env.SOLUTION_NAME }}
      - name: Build
        run: dotnet build ${{ env.SOLUTION_NAME }} --configuration Release --no-restore
      - name: Test
        if: runner.os != 'Windows'
        run: dotnet test ${{ env.SOLUTION_NAME }} --configuration Release --verbosity normal --no-build --nologo --filter FullyQualifiedName\!~IntegrationTests --collect "Code Coverage" --settings .runsettings --results-directory ./bin/TestResults --logger GitHubActions
      - name: Test windows
        if: runner.os == 'Windows'
        run: dotnet test ${{ env.SOLUTION_NAME }} --configuration Release --verbosity normal --no-build --nologo --filter FullyQualifiedName!~IntegrationTests --collect "Code Coverage" --settings .runsettings --results-directory .\bin\TestResults --logger GitHubActions
      - name: Pack
        id: pack
        if: matrix.os == 'ubuntu-latest' && (github.ref == 'refs/heads/main' || contains(github.ref, 'refs/tags/'))
        run: dotnet pack ${{ env.SOLUTION_NAME }} --configuration Release --verbosity normal --no-build --nologo --no-restore /p:Version=${{ steps.nbgv.outputs.SemVer2 }} --output ./bin/Pack/
      - name: Upload Artifact
        if: steps.pack.outcome == 'success'
        uses: actions/upload-artifact@v3.1.2
        with:
          name: nupkg
          path: |
            ./bin/Pack/*.nupkg
            ./bin/Pack/*.snupkg

  deploy:
    if: github.ref == 'refs/heads/main' || contains(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        id: download
        uses: actions/download-artifact@v3.0.2
        with:
          name: nupkg
      - name: Setup github remotes
        run: dotnet nuget add source $GITHUB_FEED --username $Owner --password $GITHUB_KEY --store-password-in-clear-text --name github
      - name: Push to GitHub Feed
        run: dotnet nuget push ${{steps.download.outputs.download-path}}/*.nupkg --source "github" --skip-duplicate --api-key $GITHUB_KEY
      - name: Push to NuGet Feed
        if: needs.build.outputs.publicRelease == 'true' && contains(github.ref, 'refs/tags/')
        run: dotnet nuget push ${{steps.download.outputs.download-path}}/*.nupkg --source $NUGET_FEED --skip-duplicate --api-key $NUGET_KEY